### ISSUE TITLE
feature request: add overload to Settings.Get to specify name of JSON file

### ISSUE THREAD

**Issue by SurajGupta** [jonsequitur/Its.Configuration#11]
I'd like to map a JSON config file to a type where the name of the file does not match the name of the type.  I don't think that that is possible?  This kind of flexibility would allow me to disambiguate two types with the same name.  Also and in general, it enables me to name my types in a way that's most appropriate for the project that those types are contained within, while getting to pick config file names that are most appropriate for the harness (console app, web service, etc.).  I think that using this feature would be a bit of a smell, but in some cases totally appropriate.

**Comment by jonsequitur** [comment]
I didn't see a test specifically calling out this scenario so I added one to demonstrate how you can do it. This is using the fairly low-level but very flexible `Settings.GetSerializedSetting`: https://github.com/jonsequitur/Its.Configuration/commit/b2e5a70d3c1e7fc57ea92b08c64644d4e4c6ee26

If you want to vary this just for a specific class, you can use `Settings.For<T>.GetSerializedSetting`.

I'd certainly be open to discussing a simpler, more convention-based approach.

**Comment by SurajGupta** [comment]
Thank you for adding that test!  This will work very well.  No need to discuss a convention-based approach.  I think this is more of a corner case; it's great that I turn some knobs at a lower-level.
