### ISSUE TITLE
Question about default location for json settings files

### ISSUE THREAD

**Issue by donners77** [jonsequitur/Its.Configuration#15]
Hi.

Thank you for making this great library available.

I am wondering if you could clarify what you mean by the settings are looked up by file name by default from the root .config folder?

The test ``Settings_are_looked_up_by_file_name_by_default_from_json_files_in_the_root_of_the_config_folder()`` says that the .config root folder is the default location.  

However, this test fails if the line ``Settings.Precedence = null;`` is commented out.

Further-more, the``default behavior check`` in the first part of the test ``Settings_precedence_set_via_an_environment_variable_overrides_app_config()`` brings back the settings from the test sub-folder.

Other tests, such as ``GetFile_uses_stated_precedence()`` prior to explicitly setting the precedence are also returning settings by default from the test sub-folder.

So, it seems like the default precedence for the location of the json settings file is actually the test sub-folder, unless the precedence is explicitly over-written with null.

Am I missing something?

Kind regards,
Craig.

**Comment by jonsequitur** [comment]
Hi Craig,

Glad you're finding it useful.

I think the piece of information that wasn't made clear here is that there's a precedence for the `Settings.Precedence` lookup. You can set it programmatically, but if you don't, Its.Configuration tries to figure it out by looking for it, in order, in:

1. an environment variable
2. app.config / web.config
3. Azure settings

Most of these tests are assuming that the app.config-specified precedence ("test|local") will be in place. The `SetUp` method calls `Settings.Reset()` to restore this prior to each test. Setting `Settings.Precedence = null` in the `Settings_are_looked_up_by_file_name_by_default_from_json_files_in_the_root_of_the_config_folder` overrides this precedence setting to verify the default if none of those are set. 

Hope that makes it clearer.

Jon

**Comment by donners77** [comment]
Thank you.
That clarifies it.
