### ISSUE TITLE
Linux has a hard time with dots in environment variables

### ISSUE THREAD

**Issue by brettmorien** [jonsequitur/Its.Configuration#17]
This applies mostly to Its.Config.Js. Out of the box, the environment variable it looks for is Its.Configuration.Precedence. Bash either doesn't support dots in environment variables, or makes it extra difficult. I'm fine customizing a local version, but this will be a gotcha for somebody down the line.

**Comment by jonsequitur** [comment]
Does this result in an exception? If so, do you have the exception type or stack trace?

**Comment by nathanboktae** [comment]
The failure will be something going [wrong here](https://github.com/jonsequitur/Its.Configuration/blob/5f537634dd5b35ae7469c245668d07fba582ae0b/its.config.js/its.config.js#L36)

Is it double-dots perhaps? What to submit a PR including even one with just the failing test?

also it may be worth it to split its.config.js out into it's own repo.

**Comment by askheaves** [comment]
It's not so much that an exception occurs, it's that you can't set the environment variable read by the code. Bash doesn't like periods in environment variable names.

```
export Its.Configuration.Precedence=staging
 -bash: export: `Its.Configuration.Precedence=staging': not a valid identifier
```

Or am I reading that right and you can just set a variable called "precedence"? Not sure that's a great idea either.
```
precedence = envVars['Its.Configuration.Precedence'] || envVars.precedence || precedence
```

**Comment by nathanboktae** [comment]
> Or am I reading that right and you can just set a variable called "precedence"?

Yes you can do that insteand of `Its.Configuration.Precedence`. IIRC it was due to the same issues (I was using cygwin in windows when using this before).

> Not sure that's a great idea either.

Why not?

**Comment by askheaves** [comment]
If you're in a pretty limited context, it's probably fine. But I wonder about just having a system variable called "precedence", for avoiding conflicts or at least for clarity.

**Comment by nathanboktae** [comment]
Perhaps - most use cases of environment variables where they are required often end up short as since you have to specify them, they will be set and override any other ambient env variable that should be more specific (like `AWS_ACCESS_KEY_ID` or `SAUCELABS_ACCOUNT_KEY`). It could be updated to `ITSCONFIGPRECEDENCE` too though it's a bit hard to read. `PRECEDENCE=stage node myapp.js` is pretty easy to type and read.
