### ISSUE TITLE
Its.Configuration cannot be used in Portable projects

### ISSUE THREAD

**Issue by piotrpMSFT** [jonsequitur/Its.Configuration#4]
Adding the NuGet package fails with:

```
Failed to add reference to 'System.ComponentModel.Composition'. 
Please make sure that it is in the Global Assembly Cache.
```

**Comment by nathanboktae** [comment]
We were just talking about axing MEF entirely the other day. I think it's time to do this - we'll probably need to do a major bump.

**Comment by nathanboktae** [comment]
oh wait that was [Its.Log](https://github.com/jonsequitur/Its.Log). The only reference here is in [`AssemblyCatalog.cs`](https://github.com/jonsequitur/Its.Configuration/blob/288c06f85af5d2ae5c897fcb88eecc7a2593f0f0/Configuration/AssembliesCatalog.cs) - should be easy enough to remove.

**Comment by jonsequitur** [comment]
Agreed. Removing the MEF references here will be a breaking change but it's something we've been wanting to do anyway.

**Comment by piotrpMSFT** [comment]
Removing the System.ComponentModel.Composition dependency is not sufficient. Installing the package into Portable projects now fails with:

    Failed to add reference to 'System.Web.Extensions'. Please make sure that it is in the Global Assembly Cache.

**Comment by nathanboktae** [comment]
Is there some tool we can use to analyze what depedencies we need to cut to make it a portable project?

**Comment by piotrpMSFT** [comment]
Yes, take a look at:
http://blogs.msdn.com/b/dotnet/archive/2014/05/12/the-next-generation-of-net-asp-net-vnext.aspx#_Targeting_Multiple_Platforms

**Comment by jonsequitur** [comment]
`System.Web.Extensions` is used here to do JSON deserialization without adding a package dependency. Thoughts on adding a dependency on `NewtonSoft.Json` for this?

**Comment by piotrpMSFT** [comment]
I don't have any projects that depend on Its.Configuration but not Newtonsoft.Json. I wonder if that's a common trend?

**Comment by nathanboktae** [comment]
ASP.NET vNext depends on `Newtonsoft.Json` - I think this is a safer bet than `System.Web.Extensions` long term.

**Comment by jonsequitur** [comment]
Updated the pull request to include this: https://github.com/jonsequitur/Its.Configuration/pull/5

**Comment by jonsequitur** [comment]
I'm reevaluating whether a portable library is appropriate for Its.Configuration. At least as the project currently stands, the pattern is very much based around file system access and a structured file drop for configurations. Making it a portable library would require a file system abstraction as well as some established patterns and use cases for other platforms. Let's collect a few of those before moving forward with this.

Suggestions are welcome.
