### ISSUE TITLE
JSON types to .NET types

### ISSUE THREAD

**Issue by joshgav** [jonsequitur/Its.Configuration#6]
Can you provide a map of JSON types to the types to be used in the C# *Settings class? E.g. JS Array -> IList<string>, JS Object -> IDictionary<string,string>.

Thanks!

**Comment by jonsequitur** [comment]
I'm not certain I fully understand the question but I'll offer a few thoughts. Please clarify for me if this isn't helpful. Are you asking about cases when `MySettings` has a property of type `IList` / `IDictionary` / etc? If so, this depends on the serializer you're using. By default `Its.Configuration` uses `System.Web.Script.Serialization.JavaScriptSerializer`, which I don't believe supports this, but you can swap out the serializer by setting `Settings.Deserialize` to a delegate that calls a different serializer. `NewtonSoft.Json` may support this behavior by convention and if not it can certainly be customized to do so.

Regarding the default serializer, this is likely changing and you may want to have a look at this discussion: https://github.com/jonsequitur/Its.Configuration/issues/4

**Comment by joshgav** [comment]
Yes, that's what I was looking for. I didn't have time to deeply review the code here so I just tried an IList<string> for an array of strings in JSON (`[ "string1", "string2" ]`) and that worked. Good to know that the serializer is configurable.

Thanks for the pointer to the other thread; Newtonsoft.Json is also my first stop for JSON in C#.
